// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-equipos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_equipos_default = defineTool({
  name: "list_equipos",
  title: "Listar equipos",
  description: "Lista equipos del inventario. Filtros opcionales por estado (disponible, contratado, taller, inactivo, baja, etc.), modelo o marca. Devuelve como m\xE1ximo 50 resultados.",
  inputSchema: {
    estado: z.string().optional().describe("Estado del equipo, ej. 'disponible'"),
    modelo: z.string().optional().describe("Filtro por modelo (b\xFAsqueda parcial)"),
    marca: z.string().optional().describe("Filtro por marca (b\xFAsqueda parcial)"),
    limit: z.number().int().min(1).max(50).optional().describe("L\xEDmite de resultados (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, modelo, marca, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("equipos").select("id, folio, modelo, marca, estado, ubicacion_actual, precio_lista").limit(limit ?? 20);
    if (estado) q = q.eq("estado", estado);
    if (modelo) q = q.ilike("modelo", `%${modelo}%`);
    if (marca) q = q.ilike("marca", `%${marca}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { equipos: data }
    };
  }
});

// src/lib/mcp/tools/get-equipo.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_equipo_default = defineTool2({
  name: "get_equipo",
  title: "Obtener equipo por folio",
  description: "Obtiene el detalle completo de un equipo espec\xEDfico por su folio.",
  inputSchema: {
    folio: z2.string().min(1).describe("Folio del equipo (ej. 'EQ-0001')")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ folio }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("equipos").select("*").eq("folio", folio).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No se encontr\xF3 equipo con folio ${folio}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { equipo: data }
    };
  }
});

// src/lib/mcp/tools/list-contratos.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contratos_default = defineTool3({
  name: "list_contratos",
  title: "Listar contratos",
  description: "Lista contratos de renta. Permite filtrar por estatus y cliente.",
  inputSchema: {
    estatus: z3.string().optional().describe("Estatus del contrato, ej. 'activo', 'finalizado'"),
    cliente: z3.string().optional().describe("Filtro por nombre de cliente (parcial)"),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estatus, cliente, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("contratos").select("id, folio, cliente_nombre, obra, fecha_inicio, fecha_fin, estatus").order("fecha_inicio", { ascending: false }).limit(limit ?? 20);
    if (estatus) q = q.eq("estatus", estatus);
    if (cliente) q = q.ilike("cliente_nombre", `%${cliente}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { contratos: data }
    };
  }
});

// src/lib/mcp/tools/list-clientes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clientes_default = defineTool4({
  name: "list_clientes",
  title: "Listar clientes",
  description: "Lista clientes registrados. Busca por nombre parcial si se provee.",
  inputSchema: {
    search: z4.string().optional().describe("B\xFAsqueda parcial por nombre"),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("clientes").select("*").order("nombre", { ascending: true }).limit(limit ?? 20);
    if (search) q = q.ilike("nombre", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clientes: data }
    };
  }
});

// src/lib/mcp/tools/inventario-resumen.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var inventario_resumen_default = defineTool5({
  name: "inventario_resumen",
  title: "Resumen de inventario",
  description: "Devuelve el conteo de equipos agrupado por estado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("equipos").select("estado");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = {};
    for (const row of data ?? []) {
      const k = row.estado ?? "desconocido";
      counts[k] = (counts[k] ?? 0) + 1;
    }
    const total = data?.length ?? 0;
    return {
      content: [{ type: "text", text: JSON.stringify({ total, por_estado: counts }, null, 2) }],
      structuredContent: { total, por_estado: counts }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xgahgclqmkfazkrowwwt";
var mcp_default = defineMcp({
  name: "comymaq-mcp",
  title: "COMYMAQ MCP",
  version: "0.1.0",
  instructions: "Herramientas para consultar el sistema COMYMAQ de renta de equipo: inventario de equipos, contratos, clientes y resumen de inventario. Todas las operaciones se ejecutan como el usuario autenticado y respetan sus permisos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_equipos_default, get_equipo_default, list_contratos_default, list_clientes_default, inventario_resumen_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
